name: US EOD Liquidity Report (Stooq-first)

on:
  workflow_dispatch: {}     # 手動実行
  schedule:
    - cron: '40 10 * * 1-5' # 19:40 JST (平日)
    - cron: '00 11 * * 1-5' # 20:00 JST (平日)

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        shell: bash
        run: |
          python -V
          python -m pip install --upgrade pip
          pip install pandas numpy requests tqdm pyarrow yfinance

      - name: Smoke test env
        shell: bash
        run: "python -c 'import pandas, numpy, yfinance; print(\"OK: imports\")'"

      - name: Run report (stooq-first; robust fallbacks)
        shell: bash
        env:
          TIINGO_API_TOKEN: ${{ secrets.TIINGO_API_TOKEN }}
          ALPHAVANTAGE_API_KEY: ${{ secrets.ALPHAVANTAGE_API_KEY }}
          FORCE_UNIVERSE_SOURCE: "yf"   # wiki無効化の最終砦
        run: |
          set -euo pipefail
          TS=$(TZ=Asia/Tokyo date +%Y%m%d)
          mkdir -p out/$TS
          python run_us_eod_liquidity_report.py \
            --N 3000 \
            --since_days 300 \
            --universe "sp500,dow30,nasdaq100" \
            --universe_source "yf" \
            --source_order "stooq,yf,tiingo,alphav" \
            --outdir out/$TS
          rm -rf out/latest && mkdir -p out/latest && cp -r out/$TS/* out/latest/

      - name: Pack single ZIP
        shell: bash
        run: |
          TS=$(TZ=Asia/Tokyo date +%Y%m%d)
          cd out && zip -rq ../us-eod-report-$TS.zip . && cd ..
          ls -lh us-eod-report-$TS.zip

      - name: Upload ZIP
        uses: actions/upload-artifact@v4
        with:
          name: us-eod-report
          path: us-eod-report-*.zip
          retention-days: 14
