name: US EOD Liquidity Report (Diag Safe)

on:
  workflow_dispatch: {}     # 手動実行用
  schedule:
    # 17:00 JST に1回のみ（= 08:00 UTC）。重複を避けるため20:00 JST のスケジュールは削除
    - cron: '0 8 * * 1-5'

concurrency:
  group: us-eod-report
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        shell: bash
        run: |
          set -euo pipefail
          python -V
          python -m pip install --upgrade pip
          pip install pandas numpy requests tqdm pyarrow yfinance
          which zip || (sudo apt-get update && sudo apt-get install -y zip)
          which dos2unix || (sudo apt-get update && sudo apt-get install -y dos2unix)
          which timeout || (sudo apt-get update && sudo apt-get install -y coreutils)

      - name: Smoke test env
        shell: bash
        run: "python -c 'import pandas, numpy, yfinance; print(\"OK: imports\")'"

      # === 公式ディレクトリをダウンロード（bash スクリプト） ===
      - name: Fetch official symbol directories
        shell: bash
        run: |
          set -euo pipefail
          bash scripts/fetch_symdirs.sh

      # === 公式ディレクトリを正規化してユニバースCSVを作成（Python スクリプト） ===
      - name: Build universe CSV from directories
        shell: bash
        run: |
          set -euo pipefail
          python3 scripts/build_universe.py

      # === レポート実行（EOD／上位流動性N銘柄、ユニバースは上のCSV、データ源は yf→tiingo→alphav） ===
      - name: Run report (EOD, top-liquidity, CSV universe, yf→tiingo→alphav)
        shell: bash
        env:
          TIINGO_API_TOKEN: ${{ secrets.TIINGO_API_TOKEN }}
          ALPHAVANTAGE_API_KEY: ${{ secrets.ALPHAVANTAGE_API_KEY }}
        run: |
          set -euo pipefail
          TS=$(TZ=Asia/Tokyo date +%Y%m%d)
          mkdir -p out/$TS
          python run_us_eod_liquidity_report.py \
            --N 1500 \
            --since_days 560 \
            --universe "sp500,nasdaq100,dow30,r1000,sp400,sp600" \
            --universe_source "file:data/universe.csv" \
            --source_order "yf,tiingo,alphav" \
            --outdir out/$TS
          # 最新コピー
          rm -rf out/latest && mkdir -p out/latest && cp -r out/$TS/* out/latest/

      - name: Pack single ZIP
        shell: bash
        run: |
          set -euo pipefail
          TS=$(TZ=Asia/Tokyo date +%Y%m%d)
          cd out && zip -rq ../us-eod-report-$TS.zip . && cd ..
          ls -lh us-eod-report-$TS.zip

      - name: Upload ZIP
        uses: actions/upload-artifact@v4
        with:
          name: us-eod-report
          path: us-eod-report-*.zip
          retention-days: 14
